/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin': RouteRecordInfo<'admin', '/admin', Record<never, never>, Record<never, never>>,
    'admin-inspectors': RouteRecordInfo<'admin-inspectors', '/admin/inspectors', Record<never, never>, Record<never, never>>,
    'admin-teams': RouteRecordInfo<'admin-teams', '/admin/teams', Record<never, never>, Record<never, never>>,
    'admin-teams-id': RouteRecordInfo<'admin-teams-id', '/admin/teams/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'analytics-executive': RouteRecordInfo<'analytics-executive', '/analytics-executive', Record<never, never>, Record<never, never>>,
    'asgroups': RouteRecordInfo<'asgroups', '/asgroups', Record<never, never>, Record<never, never>>,
    'calendar': RouteRecordInfo<'calendar', '/calendar', Record<never, never>, Record<never, never>>,
    'contractor': RouteRecordInfo<'contractor', '/contractor', Record<never, never>, Record<never, never>>,
    'contractor-users': RouteRecordInfo<'contractor-users', '/contractor/users', Record<never, never>, Record<never, never>>,
    'files': RouteRecordInfo<'files', '/files', Record<never, never>, Record<never, never>>,
    'ideas': RouteRecordInfo<'ideas', '/ideas', Record<never, never>, Record<never, never>>,
    'index-backup-original': RouteRecordInfo<'index-backup-original', '/index-backup-original', Record<never, never>, Record<never, never>>,
    'index-improved': RouteRecordInfo<'index-improved', '/index-improved', Record<never, never>, Record<never, never>>,
    'links': RouteRecordInfo<'links', '/links', Record<never, never>, Record<never, never>>,
    'map-overview': RouteRecordInfo<'map-overview', '/map-overview', Record<never, never>, Record<never, never>>,
    'operations-control': RouteRecordInfo<'operations-control', '/operations-control', Record<never, never>, Record<never, never>>,
    'orders': RouteRecordInfo<'orders', '/orders', Record<never, never>, Record<never, never>>,
    'orders-id': RouteRecordInfo<'orders-id', '/orders/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'orders-create': RouteRecordInfo<'orders-create', '/orders/create', Record<never, never>, Record<never, never>>,
    'orders-kanban': RouteRecordInfo<'orders-kanban', '/orders-kanban', Record<never, never>, Record<never, never>>,
    'panel1-backup-original': RouteRecordInfo<'panel1-backup-original', '/panel1-backup-original', Record<never, never>, Record<never, never>>,
    'panel1-variant-control-center': RouteRecordInfo<'panel1-variant-control-center', '/panel1-variant-control-center', Record<never, never>, Record<never, never>>,
    'panel1-variant-mapfocus': RouteRecordInfo<'panel1-variant-mapfocus', '/panel1-variant-mapfocus', Record<never, never>, Record<never, never>>,
    'panel2-backup-original': RouteRecordInfo<'panel2-backup-original', '/panel2-backup-original', Record<never, never>, Record<never, never>>,
    'panel2-variant-kanban': RouteRecordInfo<'panel2-variant-kanban', '/panel2-variant-kanban', Record<never, never>, Record<never, never>>,
    'panel3-backup-original': RouteRecordInfo<'panel3-backup-original', '/panel3-backup-original', Record<never, never>, Record<never, never>>,
    'panel3-variant-executive': RouteRecordInfo<'panel3-variant-executive', '/panel3-variant-executive', Record<never, never>, Record<never, never>>,
    'posts': RouteRecordInfo<'posts', '/posts', Record<never, never>, Record<never, never>>,
    'surveyor': RouteRecordInfo<'surveyor', '/surveyor', Record<never, never>, Record<never, never>>,
    'surveyor-clients': RouteRecordInfo<'surveyor-clients', '/surveyor/clients', Record<never, never>, Record<never, never>>,
    'surveyor-contractors': RouteRecordInfo<'surveyor-contractors', '/surveyor/contractors', Record<never, never>, Record<never, never>>,
    'surveyor-projects': RouteRecordInfo<'surveyor-projects', '/surveyor/projects', Record<never, never>, Record<never, never>>,
    'surveyor-tasks': RouteRecordInfo<'surveyor-tasks', '/surveyor/tasks', Record<never, never>, Record<never, never>>,
    'surveyor-users': RouteRecordInfo<'surveyor-users', '/surveyor/users', Record<never, never>, Record<never, never>>,
    'surveyor-works': RouteRecordInfo<'surveyor-works', '/surveyor/works', Record<never, never>, Record<never, never>>,
    'surveys': RouteRecordInfo<'surveys', '/surveys', Record<never, never>, Record<never, never>>,
    'trades': RouteRecordInfo<'trades', '/trades', Record<never, never>, Record<never, never>>,
    'types': RouteRecordInfo<'types', '/types', Record<never, never>, Record<never, never>>,
  }
}
